name = input("Enter your full name: ")
phone_number = input("Enter your Phone number")
# result = len(name)
# result = name.find("M")
# result = name.rfind("o")
# name = name.capitalize() 
# if first letter lower case then it capitalize it
#name = name.upper()
# name = name.lower()
# result = name.isdigit()
# result = name.isalpha()
# result = phone_number.count("-")
phone_number = phone_number.replace("-", " ")

print(phone_number)
